users/forms.py
import re

from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, PasswordField
from wtforms.validators import Email, ValidationError, Length, EqualTo, InputRequired


# checks if a field contains characters that are not allowed
def character_check(form, field):
    excluded_chars = "*?!'^+%&/()=}][{$#@<>"
    for char in field.data:
        if char in excluded_chars:
            raise ValidationError(
                f"Character {char} is not allowed.")


class RegisterForm(FlaskForm):

    firstname = StringField(validators=[InputRequired()])
    lastname = StringField(validators=[InputRequired()])
    email = StringField(validators=[InputRequired(), Email()])
    phone = StringField(validators=[InputRequired()])

    password = PasswordField(
        validators=[
            InputRequired(),
            Length(
                min=6,
                max=12,
                message="Password must be between 6 and 12 characters in length."
            )
        ]
    )
    password_confirm = PasswordField(
        validators=[
            InputRequired(),
            EqualTo("password", message="Both password fields must be equal!")
        ]
    )
    submit = SubmitField()

    def validate_password(self, password):
        p = re.compile(r'(?=.*\d)(?=.*[A-Z])(?=.*[a-z])(?=.*\W)')
        if not p.match(self.password.data):
            raise ValidationError(message="Password must contain at least 1 small letter,"
                                          " 1 capital letter, 1 digit and 1 special character.")


class LoginForm(FlaskForm):
    email = StringField(validators=[InputRequired(), Email()])
    password = PasswordField(validators=[InputRequired()])
    submit = SubmitField()

admins/views.py
import os

from firebase_admin import db
from dotenv import load_dotenv
from flask import Blueprint, render_template, redirect, url_for, request

from Functions import requiresRoles

"""
Views related to admin role:
- delete_issue
- admin

"""

admins_blueprints = Blueprint("admins", __name__, template_folder="templates")

load_dotenv()
MAP_TOKEN = os.getenv("MAP_TOKEN")

# Deletes an issue
@admins_blueprints.route("/delete_issue", methods=["POST"])
@requiresRoles.requires_roles("admin")
def delete_issue():
    ref = db.reference("/issues/")
    issues = ref.get()
    for k, v in issues.items():
        if v["id"] == int(request.form["issue-id"]):
            ref.child(k).set({})
    return redirect(url_for("admins.admin"))


# Admin view of the app
@admins_blueprints.route("/admin", methods=["POST", "GET"])
@requiresRoles.requires_roles("admin")
def admin():
    # Get categories from DB
    ref = db.reference("/categories/")
    categories = ref.get()

    # Get issues from db
    ref = db.reference("/issues/")
    issues = ref.get()
    if type(issues) == list:
        issues = [i for i in issues if i]
    else:
        issues = {k: v for k, v in issues.items() if v is not None}
    return render_template(
        "admin.html", token=MAP_TOKEN, issues=issues, categories=categories
    )

standard/views.py
import os
import json

import requests
from dotenv import load_dotenv
from firebase_admin import auth, db
from flask import Blueprint, request, session, redirect, url_for, render_template
from Functions.getRoleFromID import get_role_from_id
from users.forms import RegisterForm

"""
Standard views:
- index
- about
- register

"""

standard_blueprint = Blueprint("standard", __name__, template_folder="templates")

load_dotenv()
API_KEY = os.getenv("API_KEY")


# Main view redirects to login
@standard_blueprint.route("/")
def index():
    return redirect("home")


@standard_blueprint.route("/home")
def home():
    is_login = True if session.get("idToken", None) else False

    # map_route = None
    # if is_login:
    #     verif = auth.verify_id_token(session["idToken"])
    #     user_type = get_role_from_id(verif["uid"])
    #     if user_type == "user":
    #         map_route = "users.user"
    #     else:
    #         map_route = "admins.admin"
    # print(map_route)

    return render_template("home.html", is_login=not is_login)


# About page
# TODO : about page
@standard_blueprint.route("/about")
def about():
    return render_template("about.html")


# Register route
@standard_blueprint.route("/register", methods=["GET", "POST"])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        # if request.method == "POST":

        # TODO: validation of data
        details = {
            "email": form.email.data,
            "password": form.password.data,
            "returnSecureToken": True,
        }

        # send post request to firebase api
        r = requests.post(
            "https://identitytoolkit.googleapis.com/v1/accounts:signUp?key={}".format(
                API_KEY
            ),
            data=details,
        )

        # check for errors in result
        if "error" in r.json().keys():
            response = {"status": "error", "message": r.json()["error"]["message"]}

            return render_template(
                "register.html", errors=response["message"], form=form
            )

        # if the registration succeeded
        if "idToken" in r.json().keys():
            response = {"status": "success", "idToken": r.json()["idToken"]}
            session["idToken"] = json.dumps(response["idToken"])

            # save int the db that a new user is registered
            verif = auth.verify_id_token(response["idToken"])
            ref = db.reference("/roles/user/")
            ref.push(verif["uid"])

            return redirect(url_for("users.user"))

    return render_template("register.html", errors=None, form=form)

users/views.py
import os
import json

import requests
from firebase_admin import auth, db
from dotenv import load_dotenv
from flask import session, redirect, render_template, request, url_for, Blueprint, flash

from Functions import requiresRoles, getRoleFromID

"""
Views related to user role:
- new_issue
- score_cast
- user
- login 
- logout

"""

# CONFIG
users_blueprint = Blueprint("users", __name__, template_folder="templates")

load_dotenv()
MAP_TOKEN = os.getenv("MAP_TOKEN")
API_KEY = os.getenv("API_KEY")

# Place where new issue data is sent
@users_blueprint.route("/new_issue", methods=["POST"])
@requiresRoles.requires_roles("user")
def new_issue():
    ref = db.reference("/issues")
    issues = ref.get()

    id_ref = db.reference("/issue-id-counter")
    issue_id = id_ref.get()

    # TODO : needs a better way of calculating ids
    id = 1 + issue_id

    new_issue = {
        "category": request.form["category"],
        "color": "orange",
        "description": request.form["description"],
        "lng": request.form["lng"],
        "lat": request.form["lat"],
        "score": 1,
        "id": id,
    }

    ref.push(new_issue)
    id_ref.set(id)
    return redirect(url_for("users.user"))


# Place where new issue data is sent
@users_blueprint.route("/score_cast", methods=["POST"])
@requiresRoles.requires_roles("user")
def score_cast():
    # TODO: track user ids to not allow users vote multiple times
    ref = db.reference("/issues/")
    issues = ref.get()

    for k, v in issues.items():
        if v["id"] == int(request.form["issue-id"]):
            ref.child(k).update({"score": int(request.form["score"])})
    return redirect(url_for("users.user"))


# User view of the app
@users_blueprint.route("/user", methods=["POST", "GET"])
@requiresRoles.requires_roles("user")
def user():
    # Get categories from DB
    ref = db.reference("/categories")
    categories = ref.get()

    # Get issues from db
    ref = db.reference("/issues/")
    issues = ref.get()
    if type(issues) == list:
        issues = [i for i in issues if i]
    else:
        try:
            issues = {k: v for k, v in issues.items() if v is not None}
        except AttributeError:
            issues = []
    return render_template(
        "user.html", token=MAP_TOKEN, issues=issues, categories=categories
    )


# User login view
@users_blueprint.route("/login", methods=["POST", "GET"])
def login():
    # TODO make to accept error messages
    # Change register the sa,me
    """auth is being implemented according to this website
    https://blog.icodes.tech/posts/python-firebase-authentication.html
    """
    if request.method == "POST":

        details = {
            "email": request.form["email"],
            "password": request.form["password"],
            "returnSecureToken": True,
        }
        # Post request to firebase api
        r = requests.post(
            "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key={}".format(
                API_KEY
            ),
            data=details,
        )
        # check for errors
        if "error" in r.json().keys():
            response = {"status": "error", "message": r.json()["error"]["message"]}
            return render_template("login.html", errors=response["message"])
        # success
        if "idToken" in r.json().keys():
            response = {"status": "success", "idToken": r.json()["idToken"]}
            session["idToken"] = json.dumps(response["idToken"])

            verif = auth.verify_id_token(response["idToken"])
            user_type = getRoleFromID.get_role_from_id(verif["uid"])
            if user_type == "user":
                user_type = "users.user"
            else:
                user_type = "admins.admin"
            return redirect(url_for(user_type))
    # Error variable cvhange login
    return render_template("login.html", errors=None)


# User logout view
@users_blueprint.route("/logout")
@requiresRoles.requires_roles()
def logout():
    session["idToken"] = None
    return redirect("home")

templates/503.html
{% extends "base.html" %}

{% block content %}

     <h2 class="title is-2">Service unavailable</h2>

{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
<head>
    <title>About Us Sec</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, intial-scale=1.0">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" type="text/css" href={{ url_for('static', filename="css/stlye.css") }}>
</head>
<style>
    @import url('https://fonts.googleapis.com/css2?family=Poppins:ital,wght@1,200&display=swap');
    *{
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
}
.section{
    width: 100%;
    min-height: 100vh;
    background-color: #ddd;
}
.container{
    width: 80%;
    display: block;
    margin: auto;
    padding-top: 100px;
}
.content-section{
    float: left;
    width: 55%;
}
.image-section{
    float: right;
    width: 40%;
    position: absolute;
    top: 250px;
    right: 50px;
}
.image-section img{
    width: 350px;
    height: 400px;
}
.content-section .title{
    text-transform: uppercase;
    font-size: 15px;
    margin: 10px;
}
.content-section .content h3{
    margin-top: 10px;
    color: #5d5d5d;
    font-size: 21px;
}
.content-section .content h4{
    margin-top: 10px;
    font-family: sans-serif;
    font-size: 18px;
    line-height: 1.5;
}
@media screen and (max-width: 768px){
.container{
    width: 80%;
    display: block;
    margin: auto;
    padding-top: 100px;
}
.content-section{
    float: none;
    width: 50%;
    display: block;
    margin: auto;
}
.image-section{
    float: right;
    width: 100%;
}
.image-section img{
    width: 100%;
    height: auto;
    display: block;
    margin: auto;
}
.content-section .title{
    text-align: center;
    font-size: 19px;
}
}
        body {
	margin: 0;
	background: #222;
	font-family: 'Work Sans', sans-serif;
	font-weight: 800;


}

.container {
	width: 80%;
	margin: 0 auto;

}
header {
  background: #55d6aa;
    height: 40vh;
}
header::after {
  content: '';
  display: table;
  clear: both;
}
.logo {
  float: left;
  padding: 1px 530px;
  height: 500px;

}

nav {
  float: right;

}
nav ul {
  margin: 0;
  padding: 0;
  list-style: none;
}

nav li {
  display: inline-block;
  margin-left: 100px;
  padding-top: 23px;
  right: 160px;
  position: relative;
}
nav a {
  color: #444;
  text-decoration: none;
  text-transform: uppercase;
  font-size: 14px;
}
nav a:hover {
  color: #000;
}

nav a::before {
  content: '';
  display: block;
  height: 5px;
  background-color: #444;

  position: absolute;
  top: 0;
  width: 0;

  transition: all ease-in-out 250ms;
}

nav a:hover::before {
  width: 100%;
}
.map{
    height: 80vh;
    width: 100%;
}
</style>
    <nav class="navbar">
        <ul>
            <li><a href="{{ url_for('standard.index') }}" class="navbar-item">Home</a> </li>
            <li><a href="{{ url_for('standard.register') }}" class="navbar-item">Register</a> </li>
            <li><a href="{{ url_for('users.login') }}" class="navbar-item">Login</a> </li>
            <li><a href="{{ url_for('users.user') }}" class="navbar-item">Map</a> </li>
            <li><a href="{{ url_for('standard.about') }}" class="navbar-item">About Us</a> </li>
            <li><a href="{{ url_for('users.logout') }}" class="navbar-item">Logout</a> </li>
        </ul>
    </nav>
<body>
    <div class="section">
        <div class="container">
            <div class="content-section">
                <div class="title">
                    <h1>About us</h1>
                </div>
                <div class="content">
                    <h3>Our Mission</h3>
                    <h4>This website was created based on a Newcastle University Project. Our mission was to create a web page available
                    to everyone so that they can report any issues they may encounter during their commutes. Our goal was to
                    make sure that awareness of those issues will be spread so that everyone can be informed about them and be able to avoid
                    them. That could involve closed roads, malfunctioning traffic lights and many more issues that can appear
                    in a city's infrastructure.</h4>

                </div>
                <div class="image-section">
                    <img src="https://upload.wikimedia.org/wikipedia/commons/thumb/a/ad/University_of_Newcastle_Coat_of_Arms.svg/1200px-University_of_Newcastle_Coat_of_Arms.svg.png">
                </div>
            </div>
        </div>
        <div class="container">
            <div class="content-section">
                <div class="title">
                    <h1>Contact Us</h1>
                </div>
                <div class="content">
                    <h3>You can contact us on our personal emails wih any queries </h3>
                    <h4>Titas Janusonis<span style="padding-left:40px;">t.janusonis1@newcastle.ac.uk
</span> </h4>
                    <h4>Andreas Errikos Andreadis<span style="padding-left:40px;">A.E.Andreadis2@newcastle.ac.uk
</span></h4>
                    <h4>Bartlomiej Buba<span style="padding-left:40px;"> b.buba2@newcastle.ac.uk</span></h4>
                    <h4>Areesh Imran<span style="padding-left:40px;">a.imran1@newcastle.ac.uk</span></h4>
                    <h4>Aidan Walton<span style="padding-left:40px;">a.walton8@newcastle.ac.uk</span>
</h4>
                </div>
            </div>
        </div>
    </div>

</body>
</html>

templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />

        <!-- Tailwind CSS setup -->
        <link rel="stylesheet" href="{{url_for('static',filename='css/main.css')}}" />
        <!-- Mabox API setup -->
        <link href="https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.css" rel="stylesheet" />

        <!-- Maps API -->
        <script src="https://api.mapbox.com/mapbox-gl-js/v2.3.1/mapbox-gl.js"></script>
        <title>Whinge</title>
    </head>

    <body>
        {% block content %} {% endblock %}
    </body>
</html>

templates/home.html
<!DOCTYPE html>
<html>
  <head>
    <title>Whinge</title>
    <meta charset="utf-8" />
    <link href="https://fonts.googleapis.com/css?family=Work+Sans:400,600" />
    <meta name="viewport" content="width=device-width, intial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
      integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      type="text/css"
      href="{{ url_for('static', filename='css/stlye.css') }}"
    />
  </head>
  <style>
    @import url("https://fonts.googleapis.com/css?family=Work+Sans:400,600");
    body {
      margin: 0;
      background: #222;
      font-family: "Work Sans", sans-serif;
      font-weight: 800;
    }

    .container {
      width: 80%;
      margin: 0 auto;
    }
    header {
      background: #264653;
      display: flex;
      flex-direction: column;
      justify-content: space-around;
      height: 20vh;
    }
    header::after {
      content: "";
      display: table;
      clear: both;
    }
    .img {
      width: 100%;
      display: flex;
      flex-direction: row;
      justify-content: center;
    }
    .logo {
      height: 100px;
    }

    nav {
      margin-left: 10vw;
      display: flex;
      flex-direction: row;
      justify-content: center;
    }
    nav ul {
      margin: 0;
      padding: 0;
      list-style: none;
    }

    nav li {
      display: inline-block;
      margin-left: 100px;
      padding-top: 23px;
      right: 160px;
      position: relative;
    }
    nav a {
      color: #f4a261;
      text-decoration: none;
      text-transform: uppercase;
      font-size: 14px;
    }
    nav a:hover {
      color: #000;
    }

    nav a::before {
      content: "";
      display: block;
      height: 5px;
      background-color: #e76f51;

      position: absolute;
      top: 0;
      width: 0;

      transition: all ease-in-out 250ms;
    }

    nav a:hover::before {
      width: 100%;
    }
    .map {
      height: 80vh;
      width: 100%;
    }
  </style>
  <body>
    <header>
      <div class="container">
        <div class="img">
          <img src="../static/images/logo.png" alt="logo" class="logo" />
        </div>
        <nav class="navbar">
          <ul>
            <li>
              <a href="{{ url_for('standard.index') }}" class="navbar-item"
                >Home</a
              >
            </li>
            {% if is_login %}
            <li>
              <a href="{{ url_for('standard.register') }}" class="navbar-item"
                >Register</a
              >
            </li>
            <li>
              <a href="{{ url_for('users.login') }}" class="navbar-item"
                >Login</a
              >
            </li>
            {% endif %} {% if not is_login %}
            <li>
              <a href="{{ url_for('users.user') }}" class="navbar-item">Map</a>
            </li>
            {% endif %}
            <li>
              <a href="{{ url_for('standard.about') }}" class="navbar-item"
                >About Us</a
              >
            </li>
            {% if not is_login %}
            <li>
              <a href="{{ url_for('users.logout') }}" class="navbar-item"
                >Logout</a
              >
            </li>
            {% endif %}
          </ul>
        </nav>
      </div>
    </header>
    <div class="image-section">
      <img src="/static/images/map.png" alt="map" class="map" />
    </div>
  </body>
</html>

templates/index.html
{% extends "base.html" %} {% block content %}
<div id="map" class="h-screen"></div>
<script>
    mapboxgl.accessToken = "pk.eyJ1Ijoic3lyb3F0IiwiYSI6ImNrd2d1M2dwOTBzMHoyd21vaXUwemZsZHYifQ.qMKLv7M4w6lRtfaDopK73A";

    const helixSq = [-1.6268, 54.9729];
    const streetMap = "mapbox://styles/mapbox/streets-v11";
    const lightMap = "mapbox://styles/mapbox/light-v10";

    var map = new mapboxgl.Map({
        container: "map",
        style: streetMap,
        center: helixSq, // starting position [lng, lat]
        zoom: 15, // starting zoom
    });
</script>

<input type="button" onclick="hello()" value="run external javascript" />

{% endblock %}

templates/login.html
{% extends "base.html" %} {% block content %}

<div id="login" class="relative flex">
    <div id="card" class="bg-white shadow-md px-4 py-8 rounded-3xl w-80 max-w-md absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2">
        <form action="{{url_for('users.login')}}" method="post">
            <div id="title" class="font-medium self-center text-xl sm:text-3xl text-gray-800">
                Login to Whinge
            </div>

            <!-- Email -->
            <div class="mb-4 mt-4">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="email">
                    Email
                </label>
                <input class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline" id="email" name="email" type="email" required placeholder="email@example.io" />
            </div>
            <!-- Password -->
            <div class="mb-6">
                <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
                    Password
                </label>
                <input
                    class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
                    id="password"
                    name="password"
                    required
                    type="password"
                    placeholder="******************"
                />
            </div>
            <!-- Bottom part -->
            <div class="flex flex-row justify-around">
                <button type="submit">Submit</button>
                <a href="{{url_for('standard.register')}}">Register</a>
            </div>
            {% if errors %}
            <p class="mt-5 text-red-800"><b>{{errors}}</b></p>
            {% endif %}
        </form>
    </div>
</div>

<style>
    body {
        background-color: #264653;
    }
    #login {
        height: 100vh;
    }

    button,
    a {
        border-radius: 28px;
        display: inline-block;
        cursor: pointer;
        color: #ffffff;
        font-family: Arial;
        font-size: 17px;
        padding: 16px 31px;
        text-decoration: none;
    }

    button:hover {
        background-color: #3cc7b7;
    }
    a:hover {
        background-color: #facb53;
    }

    button:active,
    a:active {
        position: relative;
        top: 1px;
    }

    button {
        background-color: #2a9d8f;
        border: 1px solid #10695f;
    }

    a {
        background-color: #dbb145;
        border: 1px solid #b9922d;
    }

    input:focus {
        background-color: #5fd3c570;
    }
</style>

{% endblock %}

templates/user.html
{% extends "base.html" %} {% block content %}
<!-- User view and its functionality 
written in vanila JS
please don't write your css, js, and html code in a html file. 

-->

<!-- Style link -->
<link rel="stylesheet" href="{{url_for('static', filename='css/user-styles.css')}}" />
<!-- JS link -->
<script type="text/javascript" src="{{url_for('static',filename='src/user.js')}}"></script>

<!-- HMTL -->
<div id="main">
    <!-- Map -->
    <div id="map" class="h-screen relative z-0"></div>

    <!-- Menu -->
    <div>
        <img src="{{url_for('static', filename='src/assets/iconmonstr-menu-5.svg')}}" alt="Menu" id="menu" class="absolute bottom-0 left-0 w-20 h-20 mb-8 ml-6" />
    </div>

    <!-- Issue card -->
    <div id="card" class="flex-col bg-white shadow-md px-4 sm:px-6 md:px-8 lg:px-10 py-8 rounded-3xl w-80 max-w-md absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 hidden">
        <div id="issue-id" class="font-medium self-center text-xl sm:text-3xl text-gray-800">
            Here goes id
        </div>

        <div id="issue-description" class="mt-4 self-center text-xl sm:text-sm text-gray-800">
            This is a place for a short description
        </div>

        <div id="issue-category" class="mt-4 self-center text-xl sm:text-sm text-gray-800">
            This place is a category
        </div>

        <!-- Botom part of the card -->
        <div class="vertical-flex" id="voting">
            <p id="score"></p>

            <form action="{{url_for('users.score_cast')}}" , method="POST" id="downvote">
                <a id="downvote-a" href="#">
                    <img id="downvote-svg" class="vote-btn" src="{{url_for('static', filename='src/assets/iconmonstr-arrow-65.svg')}}" alt="" />
                </a>
                <input type="hidden" name="issue-id" id="down-issue-id-input" />
                <input type="hidden" name="score" id="down-score" />
            </form>

            <form action="{{url_for('users.score_cast')}}" , method="POST" id="upvote">
                <a id="upvote-a" href="#">
                    <img id="upvote-svg" class="vote-btn" src="{{url_for('static', filename='src/assets/iconmonstr-arrow-66.svg')}}" alt="" />
                </a>
                <input type="hidden" name="issue-id" id="up-issue-id-input" />
                <input type="hidden" name="score" id="up-score" />
            </form>
        </div>
    </div>

    <!-- Menu card popup -->
    <div id="menu-screen">
        <ul id="menu-items">
            <li><a href="{{url_for('standard.about')}}">About</a></li>
            <li><a href="{{url_for('users.logout')}}">Logout</a></li>
        </ul>
    </div>

    <!-- New issue -->
    <div id="new-issue" class="flex-col bg-white shadow-md px-4 sm:px-6 md:px-8 lg:px-10 py-8 rounded-3xl w-80 max-w-md absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 hidden">
        <form action="{{url_for('users.new_issue')}}" , method="POST">
            <div class="font-medium mb-4 self-center text-xl sm:text-3xl text-gray-800">
                Create a new issue
            </div>
            <label for="new-description">Description</label>
            <textarea id="new-description" required name="description" cols="32" rows="3"></textarea>

            <div id="issue-category" class="mb-4 self-center text-xl sm:text-sm text-gray-800">
                <label for="category" class="mb-4">Select the category</label>
                <select name="category" id="category">
                    {% for category in categories %}
                    <option value="{{category}}"> {{category}} </option>
                    {% endfor %}
                </select>
            </div>

            <!-- Botom part of the card -->
            <button class="btn mt-4">
                Submit
            </button>
            <input type="hidden" name="lng" id="lng" />
            <input type="hidden" name="lat" id="lat" />
        </form>
    </div>

    <!-- This backdrop functions as a back button -->
    <div id="drop"></div>
</div>

<!-- JS -->
<script>
    init();
    mapboxgl.accessToken = "{{token}}";

    // Map center is helixSq
    const helixSq = [-1.6268, 54.9729];
    const streetMap = "mapbox://styles/mapbox/streets-v11";

    // Transforming issue data from backend
    const pins = JSON.parse('{{ issues | tojson | safe}}');
    const card = document.getElementById("card");

    // Loading the map
    var map = new mapboxgl.Map({
        container: "map",
        style: streetMap,
        center: helixSq, // starting position [lng, lat]
        zoom: 15, // starting zoom
    });

    // Setup event handlers
    map.on("style.load", function () {
        // Adding a new issue
        map.on("click", function (e) {
            const coordinates = e.lngLat;
            const newIssue = document.getElementById("new-issue");
            const card = document.getElementById("card");

            if (card.style.display === "none" || card.style.display === "") {
                newIssueHandler(e);
            }
        });

        // Pin draw and setup
        for (let [key, pin] of Object.entries(pins)) {
            const el = new mapboxgl.Marker({ color: pin.color }).setLngLat([pin.lng, pin.lat]).addTo(map);

            // Save the pin data for the element
            for (let [key, value] of Object.entries(pin)) {
                el.getElement().setAttribute("data-" + key, value);
            }
            // Add the event listener
            el.getElement().addEventListener("click", pinClickHandler);
        }
    });
</script>

{% endblock %}